services:
  mcp-server:
    image: mcp-server:latest
    build:
      context: .
      dockerfile: mcp-server/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/app/workspace
    healthcheck:
      test: ["CMD", "/venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONPATH=/app

  middleware:
    image: middleware:latest
    build:
      context: .
      dockerfile: middleware/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./.env:/app/.env:ro
      - ./system_prompt.md:/app/system_prompt.md:ro
    depends_on:
      mcp-server:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      - MCP_SERVER_URL=http://mcp-server:8000
      - PYTHONPATH=/app

  sandbox:
    image: sandbox:latest
    build:
      context: .
      dockerfile: sandbox/Dockerfile
    healthcheck:
      test: ["CMD", "/venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONPATH=/app

  time-client:
    image: time-client:latest
    build:
      context: .
      dockerfile: time-client/Dockerfile
    healthcheck:
      test: ["CMD", "/venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8003/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PYTHONPATH=/app

  code-executor:
    build:
      context: .
      dockerfile: code-executor/Dockerfile
    volumes:
      - ./code-executor/app:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      sandbox:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/docker-data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    restart: unless-stopped

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    ports:
      - "8080:8080"
    volumes:
      - ./mcpo-config.json:/app/config.json:ro
    command: ["--port", "8080", "--api-key", "your-secret-key", "--config", "/app/config.json"]
    depends_on:
      mcp-server:
        condition: service_healthy
      time-client:
        condition: service_healthy
      sandbox:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - default

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3001:8080"
    volumes:
      - ./data/open-webui:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=http://ollama:11434/v1
      - OPENAI_API_KEY=ollama
      - ENABLE_OPENAI_API=true
    depends_on:
      ollama:
        condition: service_started
      mcpo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

 