global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Core MCP Services
  - job_name: 'sandbox'
    static_configs:
      - targets: ['sandbox:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'time-client'
    static_configs:
      - targets: ['time-client:8003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'diffusion-api'
    static_configs:
      - targets: ['diffusion-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'style-browser'
    static_configs:
      - targets: ['style-browser:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s 